apiVersion: v1
kind: Service
metadata:
  name: ai-dev-asst-api
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: ai-dev-asst-api
  ports:
    - name: http
      port: 80
      targetPort: http
